{***************************************************************************}
{                                                                           }
{           Delphi Package Manager - DPM                                    }
{                                                                           }
{           Copyright © 2019 Vincent Parrett and contributors               }
{                                                                           }
{           vincent@finalbuilder.com                                        }
{           https://www.finalbuilder.com                                    }
{                                                                           }
{                                                                           }
{***************************************************************************}
{                                                                           }
{  Licensed under the Apache License, Version 2.0 (the "License");          }
{  you may not use this file except in compliance with the License.         }
{  You may obtain a copy of the License at                                  }
{                                                                           }
{      http://www.apache.org/licenses/LICENSE-2.0                           }
{                                                                           }
{  Unless required by applicable law or agreed to in writing, software      }
{  distributed under the License is distributed on an "AS IS" BASIS,        }
{  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. }
{  See the License for the specific language governing permissions and      }
{  limitations under the License.                                           }
{                                                                           }
{***************************************************************************}

unit DPM.Core.Dependency.LockFile;

{
 Lock files are dependency graphs serialized in the package cache
 folder when the package cache is compiled. This allows us to see
 whether the compiled version of a cached package is fully compatible
 or if we need to recompile it.

 This is a time saving thing, avoid recompiling every package when we
 run dpm restore on a project speeds up project loading a lot.

}


interface

uses
  DPM.Core.Dependency.Interfaces;

type
  TLockFile = class
  public
    class function LoadFromFile(const fileName : string) : IGraphNode;
    class function SaveToFile(const fileName : string; const graphNode : IGraphNode) : boolean;
  end;

implementation

uses
  System.Classes,
  System.SysUtils,
  DPM.Core.Dependency.Graph;

const
  cLockFileHeader = '# DPM LockFile' + #13#10 + '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.';

{ TLockFile }

class function TLockFile.LoadFromFile(const fileName: string): IGraphNode;
var
  sList : TStringList;
begin
  result := nil;
  sList := TStringList.Create;
  try
    sList.LoadFromFile(fileName, TEncoding.UTF8);

  finally
    sList.Free;
  end;

end;

class function TLockFile.SaveToFile(const fileName: string; const graphNode: IGraphNode): boolean;
var
  sList : TStringList;

  procedure AddNode(const node : IGraphNode; level : integer);
  var
    space : string;
    childNode : IGraphNode;
  begin
    if level > 0 then
      space := StringOfChar(' ', level);
    sList.Add(space + node.Id + ':' + node.SelectedVersion.ToStringNoMeta);
    if node.HasChildren then
    begin
      Inc(level);
      for childNode in node.ChildNodes do
        AddNode(childNode, level);
    end;
  end;

begin
  result := false;
  sList := TStringList.Create;
  try
    sList.Add(cLockFileHeader);
    AddNode(graphNode, 0);

    sList.SaveToFile(fileName,TEncoding.UTF8);
  finally
    sList.Free;
  end;

end;

end.
