dpm pack .\A\VSoft.A.dspec -version=0.0.1 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.2 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.3 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.4 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.5 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.6 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.7 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.8 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.9 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.11 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.0.12 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.1.0 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.1.2 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.1.3 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.1.4 -outputFolder=%1
dpm pack .\A\VSoft.A.dspec -version=0.1.5 -outputFolder=%1


dpm pack .\B\VSoft.B.dspec -version=0.0.1 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.2 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.3 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.4 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.5 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.6 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.7 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.8 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.9 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.11 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.0.12 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.1.0 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.1.2 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.1.3 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.1.4 -outputFolder=%1
dpm pack .\B\VSoft.B.dspec -version=0.1.5 -outputFolder=%1

dpm pack .\C\VSoft.C.dspec -version=0.0.1 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.2 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.3 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.4 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.5 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.6 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.7 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.8 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.9 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.11 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.0.12 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.1.0 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.1.2 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.1.3 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.1.4 -outputFolder=%1
dpm pack .\C\VSoft.C.dspec -version=0.1.5 -outputFolder=%1

dpm pack .\D\VSoft.D.dspec -version=0.0.1 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.2 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.3 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.4 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.5 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.6 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.7 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.8 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.9 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.11 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.0.12 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.1.0 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.1.2 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.1.3 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.1.4 -outputFolder=%1
dpm pack .\D\VSoft.D.dspec -version=0.1.5 -outputFolder=%1

