{***************************************************************************}
{                                                                           }
{           Delphi Package Manager - DPM                                    }
{                                                                           }
{           Copyright � 2019 Vincent Parrett and contributors               }
{                                                                           }
{           vincent@finalbuilder.com                                        }
{           https://www.finalbuilder.com                                    }
{                                                                           }
{                                                                           }
{***************************************************************************}
{                                                                           }
{  Licensed under the Apache License, Version 2.0 (the "License");          }
{  you may not use this file except in compliance with the License.         }
{  You may obtain a copy of the License at                                  }
{                                                                           }
{      http://www.apache.org/licenses/LICENSE-2.0                           }
{                                                                           }
{  Unless required by applicable law or agreed to in writing, software      }
{  distributed under the License is distributed on an "AS IS" BASIS,        }
{  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. }
{  See the License for the specific language governing permissions and      }
{  limitations under the License.                                           }
{                                                                           }
{***************************************************************************}

unit DPM.Core.Project.CopyLocalTargets;

interface

uses
  DPM.Core.Logging;

const
  //File name written into the cache root and imported by DPM-managed dprojs as
  //$(DPMCache)\DPM.CopyLocal.targets - see TProjectEditor.EnsureCopyLocalImport.
  cCopyLocalTargetsFileName = 'DPM.CopyLocal.targets';

  //Bump when the targets content below changes so EnsureCopyLocalTargets rewrites stale copies.
  cCopyLocalTargetsVersion = '2';

//Returns the full text of DPM.CopyLocal.targets (CRLF line endings, version-marked).
function GetCopyLocalTargetsContent : string;

//Writes DPM.CopyLocal.targets into the cache root if it is absent or an older version. Idempotent
//and safe to call on every restore/install. Failures are logged as warnings, never raised - a
//missing targets file simply means copy-local does nothing (the dproj import is Exists()-guarded).
procedure EnsureCopyLocalTargets(const cacheRoot : string; const logger : ILogger);

implementation

uses
  System.SysUtils,
  System.IOUtils;

const
  //The Exec Command must stay on a single line - MSBuild turns embedded newlines into separate
  //batch lines, which breaks the command. $(DPMExe) is the restore-recorded dpm.exe path; when it
  //is missing/stale the command falls back to 'dpm' on PATH.
  cVersionMarker = '<!-- DPM.CopyLocal.targets v' + cCopyLocalTargetsVersion + ' - generated by DPM, do not edit. -->';

function GetCopyLocalTargetsContent : string;
const
  CRLF = #13#10;
begin
  //We hook the build by appending DPMCopyLocal to $(BuildDependsOn) rather than using
  //Target AfterTargets="Build". BeforeTargets/AfterTargets on <Target> require the MSBuild 4.0
  //engine - Delphi XE2..10.2 Tokyo build with FrameworkVersion v3.5 (MSBuild 3.5) which rejects
  //the attribute ("The attribute AfterTargets in element Target is unrecognized"). Appending to
  //$(BuildDependsOn) is the pre-4.0 extension pattern and is non-destructive (additive, never an
  //override) and works on every supported compiler. This relies on the dproj importing this file
  //AFTER CodeGear.Delphi.Targets (TProjectEditor.EnsureCopyLocalImport appends the Import as the
  //last child of <Project>), so $(BuildDependsOn) is already defined when we extend it.
  result :=
    '<?xml version="1.0" encoding="utf-8"?>' + CRLF +
    cVersionMarker + CRLF +
    '<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">' + CRLF +
    '  <PropertyGroup Condition="''$(DPMCopyLocalDisable)'' != ''true''">' + CRLF +
    '    <BuildDependsOn>$(BuildDependsOn);DPMCopyLocal</BuildDependsOn>' + CRLF +
    '  </PropertyGroup>' + CRLF +
    '  <Target Name="DPMCopyLocal">' + CRLF +
    '    <PropertyGroup>' + CRLF +
    '      <_DPMExe Condition="''$(DPMExe)'' != '''' and Exists(''$(DPMExe)'')">$(DPMExe)</_DPMExe>' + CRLF +
    '      <_DPMExe Condition="''$(_DPMExe)'' == ''''">dpm</_DPMExe>' + CRLF +
    //$(OutputPath) is the item transform @(OutputFile->'%(FullPath)') - the exe path, not its
    //folder - so take the directory straight from the OutputFile item metadata. (Item refs are
    //evaluated in a property value, but not inside a property function like GetDirectoryName.)
    '      <_DPMOutputDir>@(OutputFile->''%(RootDir)%(Directory)'')</_DPMOutputDir>' + CRLF +
    '    </PropertyGroup>' + CRLF +
    '    <Exec ContinueOnError="true" Command="&quot;$(_DPMExe)&quot; copylocal &quot;$(MSBuildProjectFullPath)&quot;' +
            ' -platform=$(Platform) -config=$(Config) -outputDir=&quot;$(_DPMOutputDir)&quot;' +
            ' -compiler=$(DPMCompiler) -usePackages=$(UsePackages) -runtimePackages=&quot;$(DCC_UsePackage)&quot;" />' + CRLF +
    '  </Target>' + CRLF +
    '</Project>' + CRLF;
end;

procedure EnsureCopyLocalTargets(const cacheRoot : string; const logger : ILogger);
var
  targetsFile : string;
  existing : string;
begin
  if cacheRoot = '' then
    exit;
  targetsFile := TPath.Combine(cacheRoot, cCopyLocalTargetsFileName);
  try
    if TFile.Exists(targetsFile) then
    begin
      existing := TFile.ReadAllText(targetsFile);
      //if the current version marker is already present there is nothing to do.
      if Pos(cVersionMarker, existing) > 0 then
        exit;
    end;
    if not TDirectory.Exists(cacheRoot) then
      TDirectory.CreateDirectory(cacheRoot);
    TFile.WriteAllText(targetsFile, GetCopyLocalTargetsContent, TEncoding.UTF8);
    logger.Debug('Wrote copy-local targets file [' + targetsFile + '].');
  except
    on e : Exception do
      logger.Warning('Unable to write copy-local targets file [' + targetsFile + ']: ' + e.Message);
  end;
end;

end.
