dpm install %1 dpm.dproj -version=%2 -compiler=13
dpm install %1 dpm.core.tests.dproj -version=%2 -compiler=13
dpm install %1 DSpecCreator\DspecCreator.dproj -version=%2 -compiler=13
dpm install %1 dpm.ide.d130.dproj -version=%2 -compiler=13
dpm install %1 dpm.ide.d120.dproj -version=%2 -compiler=12
dpm install %1 dpm.ide.d110.dproj -version=%2 -compiler=11
dpm install %1 dpm.ide.d104.dproj -version=%2 -compiler=10.4
dpm install %1 dpm.ide.d103.dproj -version=%2 -compiler=10.3
dpm install %1 dpm.ide.d102.dproj -version=%2 -compiler=10.2
dpm install %1 dpm.ide.d101.dproj -version=%2 -compiler=10.1
dpm install %1 dpm.ide.d100.dproj -version=%2 -compiler=10.0
dpm install %1 dpm.ide.xe8.dproj -version=%2 -compiler=XE8
dpm install %1 dpm.ide.xe7.dproj -version=%2 -compiler=XE7
dpm install %1 dpm.ide.xe6.dproj -version=%2 -compiler=XE6
dpm install %1 dpm.ide.xe5.dproj -version=%2 -compiler=XE5
dpm install %1 dpm.ide.xe4.dproj -version=%2 -compiler=XE4
dpm install %1 dpm.ide.xe3.dproj -version=%2 -compiler=XE3
dpm install %1 dpm.ide.xe2.dproj -version=%2 -compiler=XE2
